#! /usr/bin/env bash
#
# run-example wrapper script.

# Script location
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Load global paths
source "${SCRIPT_DIR}/infrastructure/paths.sh"

# Activate the python venv
activate_venv

# Just in case, for uxas-ada. A bit ugly and special-purpose. Use build-env to
# avoid directly putting uxas-ada itself on the path (in case there's a local 
# build)
debug_and_run "eval \"\$( \"${OPENUXAS_ROOT}/anod\" printenv uxas-ada --build-env )\""
debug_and_run "python3 \"${INFRASTRUCTURE_DIR}/run-example.py\" $*"
