#! /usr/bin/env bash
#
# install wrapper script.

ARGS=$@

# Script location
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Load global paths
source "${SCRIPT_DIR}/paths.sh"

( cd "${OPENUXAS_ROOT}" && python3 "${INSTALL_LIBEXEC_DIR}/install.py" ${ARGS} )
