on:
    push:
        paths:
            - 'infrastructure/install-libexec/**'
    pull_request:
        paths:
            - 'infrastructure/install-libexec/**'
    workflow_dispatch:
    schedule:
        - cron : '40 3 * * 4'

name: Check Infrastructure Install
jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                env: [
                    {os: ubuntu-20.04, python: '3.8'},
                    {os: ubuntu-22.04, python: '3.10'}
                ]
        runs-on: ${{ matrix.env.os }}
        steps:
            - uses: actions/checkout@v2
              with:
                  path: OpenUxAS

            - name: Set up python ${{ matrix.env.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.env.python }}

            - name: Set up testing tools
              run: |
                  pip install --upgrade pip
                  pip install tox

            - name: Run testsuite and style checks
              run: |
                  cd OpenUxAS/infrastructure/install-libexec
                  tox
