on:
    push:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'infrastructure/specs/**'
            - 'anod'
            - 'src/cpp/**'
            - 'tests/cpp/**'
    pull_request:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'anod'
            - 'src/cpp/**'
            - 'tests/cpp/**'
    workflow_dispatch:
    schedule:
        - cron: '20 3 * * 4'

name: Build and Test UxAS C++
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04]
                component: [uxas]
                qualifier: [scenario=release, scenario=gcov]
                python-version: [3.7, 3.8]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
              with:
                  path: OpenUxAS

            - name: Set up python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Set up java
              uses: actions/setup-java@v1
              with:
                  java-version: '11'

            - name: Install infrastructure
              run: |
                  cd OpenUxAS
                  infrastructure/install -vv --no-gnat --no-java -y

            - name: Build OpenUxAS C++
              run: |
                  cd OpenUxAS
                  ./anod -v build ${{ matrix.component }} --qualifier=${{ matrix.qualifier}}

            - name: Test OpenUxAS C++
              run: |
                  cd OpenUxAS/tests/cpp
                  ./run-tests --qualifier=${{ matrix.qualifier}}
